{% set name = "sphinx-panels" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7b3faa05f37b7318fd14cd85c4effa1ab905dfc8bed236a63978565ea461ae4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip >=3.6
    - python
  run:
    - docutils
    - python >=3.6
    - sphinx >=2,<4

test:
  imports:
    - sphinx_panels

about:
  home: https://github.com/executablebooks/sphinx-panels
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A sphinx extension for creating panels in a grid layout.
  doc_url: https://sphinx-panels.readthedocs.io/

extra:
  recipe-maintainers:
    - chrisjsewell
